### ISSUE TITLE
Velocity editing

### ISSUE THREAD

**Issue by Niko24708** [MajestikButter/Scoreboard-Expansion#1]
In this newest version, trying to edit your velocity doesn't work and resets it back to original instantly

**Comment by MajestikButter** [comment]
> Changed Velocity types to reflect recent changes disabling the ability to set player velocity

I sadly had to disable editing player velocity for the moment because there was a change made to scripting that broke the workaround I used to edit player velocity. Once there's an official way for me to edit player velocity, I will be adding it back.
